server:
  port: 8081

spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/productDB
    username: postgres
    password: 123qwe
    driverClassName: org.postgresql.Driver
  sql:
    init:
      platform: postgres

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0

